spring:
  datasource:
    url: ${URL:jdbc:localhost:3306}
    username: ${username:root}
    password: ${password:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

  output:
    ansi:
      enabled: never

certificate:
  template:
    path: ${CERTIFICATE_TEMPLATE_PATH:certificate-template/Certificate.pdf}
  output:
    directory: ${CERTIFICATE_OUTPUT_DIRECTORY:./certificates}

jwt:
  access-token:
    expiration: 15m
  refresh-token:
    expiration: 7d # 7 days
